version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: bbs
      MYSQL_ROOT_PASSWORD: root
    container_name: 'bbs-mysql'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - app-net

  api:
    build: ./php
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db
    container_name: 'bbs-php'
    networks:
      - app-net

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/html
    depends_on:
      - api
    container_name: 'nginx'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge